.PHONY: lint fmt help test lock setup train
.DEFAULT_GOAL := help

lint: ## Run Linter
	uv run ruff check .
	uv run mypy .

fmt: ## Run formatter
	uv run ruff check --fix .
	uv run ruff format .

test: ## Run tests
	uv run pytest .

lock: ## Lock dependencies
	uv lock

install: ## Setup the project
	uv sync --all-groups

run-local: # run locally
	uv run python main.py

help: # Show help for each of the Makefile recipes.
	@grep -E '^[a-zA-Z0-9 -]+:.*#'  Makefile | sort | while read -r l; do printf "\033[1;32m$$(echo $$l | cut -f 1 -d':')\033[00m:$$(echo $$l | cut -f 2- -d'#')\n"; done
