[tool.ruff]
target-version = "py311"
line-length = 100

[tool.ruff.lint]
extend-select = ["I"]

[tool.mypy]
python_version = "3.11"
exclude = [".venv"]

[[tool.mypy.overrides]]
module = "google_crc32c"
ignore_missing_imports = true
