name: Billing Reporter Deploy
on:
  push:
    branches:
      - "main"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  billing-reporter-deply:
    permissions:
      id-token: "write"
      contents: "read"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pipenv"
      - name: Install pipenv
        run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
      - name: Create requirements.txt
        run: pipenv requirements > requirements.txt
      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v2.1.3"
        with:
          workload_identity_provider: ${{ vars.GH_GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.GH_GCP_SERVICE_ACCOUNT }}
      - id: "deploy"
        uses: "google-github-actions/deploy-cloud-functions@v2"
        with:
          name: "billing-reporter"
          project_id: ${{ vars.GCP_PROJECT_ID }}
          region: "us-central1"
          runtime: "python311"
          entry_point: "main"
          source_dir: "src"
          description: "Report GCP cost to the slack channel"
          service_account_email: ${{ vars.BILLING_REPORTER_GCP_SERVICE_ACCOUNT }}
          memory_mb: "256"
          event_trigger_type: "providers/cloud.pubsub/eventTypes/topic.publish"
          event_trigger_resource: ${{ vars.BILLING_REPORTER_PUBSUB_TOPIC }}
