name: Billing Reporter Deploy
on:
  push:
    branches:
      - "main"
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  billing-reporter-deploy:
    permissions:
      id-token: "write"
      contents: "read"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-dependency-glob: "app/pyproject.toml"
      - name: Create requirements.txt
        run: uv export --format=requirements.txt > requirements.txt
      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v3.0.0"
        with:
          workload_identity_provider: ${{ vars.GH_GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.GH_GCP_SERVICE_ACCOUNT }}
      - id: "deploy"
        uses: "google-github-actions/deploy-cloud-functions@v4"
        with:
          name: "billing-reporter"
          project_id: ${{ vars.GCP_PROJECT_ID }}
          region: "us-central1"
          runtime: "python314"
          entry_point: "main"
          source_dir: "app"
          description: "Report GCP cost to the slack channel"
          service_account: ${{ vars.BILLING_REPORTER_GCP_SERVICE_ACCOUNT }}
          min_instance_count: 0
          max_instance_count: 1
          memory: "256Mi"
          event_trigger_type: "google.cloud.pubsub.topic.v1.messagePublished"
          event_trigger_pubsub_topic: ${{ vars.BILLING_REPORTER_PUBSUB_TOPIC }}
