name: Python CI
on:
  pull_request:
    paths:
      - "app/**"
  push:
    branches:
      - "main"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  python-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: "app/pyproject.toml"
      - name: Install the project
        run: make install
      - name: Lint
        run: make lint
