name: Terraform Lint
on:
  pull_request:
    paths:
      - "terraform/**"
jobs:
  terraform-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Cache plugin dir
        id: cache-plugin
        uses: actions/cache@v3
        with:
          path: ~/.tflint.d/plugins
          key: tflint-${{ hashFiles('terraform/.tflint.hcl') }}
      - name: Setup Terraform Lint
        uses: terraform-linters/setup-tflint@v3
        if: steps.cache-plugin.outputs.cache-hit != 'true'
        with:
          tflint_version: v0.46.1
      - name: Lint with tflint
        working-directory: terraform
        run: tflint --recursive
      - name: Lint with tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          working_directory: terraform
